class ConfigUtils:
    IS_DEBUG = True

    CROCODDYL_FORCE_SCALING_FACTOR = 0.0001

    PYBULLET_SIM_TIME_TOTAL = 5  # seconds
    PYBULLET_SIM_TIME_STEP = 1. / 240.

    PYBULLET_SIM_JUMP = 10
    PYBULLET_SIM_WALK = 2

    PYBULLET_POS_THRESHOLD = 0.5
    PYBULLET_ROT_THRESHOLD = 10
    PYBULLET_FORCE_MAG_MULTIPLIER = .1

    STIMULI_PLATFORM_MASS = 20.0
    STIMULI_PLATFORM_GAP = 1.2

    NAV_MODEL_VIEW_DYNAMICS = True
    NAV_MODEL_VIEW_KINEMATICS = False
    NAV_MODEL_THRESHOLD_STOP = 1e-7

    NAV_MODEL_SINGLE_PLATFORM_MULTIPLIER = 8

    NAV_MODEL_SIGMA = .5
    NAV_MODEL_ALPHA = -1

    NAV_MODEL_JUMP_HEIGHT = 2
    NAV_MODEL_STEP_HEIGHT = .1
    NAV_MODEL_STEP_LENGTH = .5

    NAV_PROBLEM_TIME_STEP = 0.02
    NAV_PROBLEM_FRICTION_COEFFICIENT = 0.7

    JUMP_GROUND_KNOTS = 20
    JUMP_FLYING_KNOTS = 20

    WALK_STAND_KNOTS = 4
    WALK_TREAD_KNOTS = 20
