class NavConfig:
    VIEW_KINEMATICS = False

    DEBUG_KINEMATICS = False
    DEBUG_DYNAMICS = True

    FRICTION_COEFFICIENT = 0.7
    TIME_STEP = 0.02

    SMALL_SKEW_SIGMA = 0.25
    LARGE_SKEW_SIGMA = 0.50

    SEARCH_RADIUS = 2.0

    MAX_TASKS_PER_PLAN = 10

    MAX_JUMP_LENGTH = 5.5
    MAX_JUMP_HEIGHT = 2.0

    MAX_STEP_LENGTH = 1.0
    MAX_STEP_HEIGHT = 0.1

    JUMP_GROUND_KNOTS = 20
    JUMP_FLYING_KNOTS = 20

    WALK_STAND_KNOTS = 4
    WALK_TREAD_KNOTS = 20

    MIN_PLATFORM_PADDING = 0.125

    DYNAMICS_THRESHOLD = 1e-7


class CrocoddylConfig:
    CROCODDYL_FORCE_SCALING_FACTOR = 0.0001
    
    
class MujocoConfig:
    FORCE_SCALE = .1


class StimuliConfig:
    MIN_GAP_X = 1.2

    GROUND_LENGTH = 30
    GROUND_WIDTH = 8
    GROUND_HEIGHT = 0.25


class PlatformConfig:
    PLATFORM_MASS_WOODY = 10.00
    PLATFORM_MASS_STONE = 20.00

    PLATFORM_HEIGHT = 3.5
    PLATFORM_SIZE_BASE = 3.0
    PLATFORM_SIZE_SLIM = 2.0
    PLATFORM_SIZE_BULK = 4.0
    PLATFORM_SIZE_WALK = 8.0

    PLATFORM_SCALE_TOP_FACTOR = .5
    PLATFORM_SCALE_BOT_FACTOR = .4

    PLATFORM_BEVEL_WIDTH = 0.75
    PLATFORM_BEVEL_SEGMENTS = 20

    PLATFORM_MESH_TYPE = ".stl"


class BlenderConfig:
    VIDEO_FRAME_COUNT = 110
