class CoreConfig:
    IS_DEBUG = True

    PYBULLET_SIM_TIME_TOTAL = 5  # seconds
    PYBULLET_SIM_TIME_STEP = 1. / 240.

    PYBULLET_SIM_JUMP = 10
    PYBULLET_SIM_WALK = 2

    PYBULLET_POS_THRESHOLD = 0.5
    PYBULLET_ROT_THRESHOLD = 10
    PYBULLET_FORCE_MAG_MULTIPLIER = .1

    NAV_MODEL_VIEW_DYNAMICS = True
    NAV_MODEL_VIEW_KINEMATICS = False
    NAV_MODEL_THRESHOLD_STOP = 1e-7

    NAV_MODEL_SINGLE_PLATFORM_MULTIPLIER = 8

    NAV_MODEL_SIGMA = .5
    NAV_MODEL_ALPHA = -1

    NAV_MODEL_JUMP_HEIGHT = 2
    NAV_MODEL_STEP_HEIGHT = .15
    NAV_MODEL_STEP_LENGTH = .75

    NAV_PROBLEM_TIME_STEP = 0.02
    NAV_PROBLEM_FRICTION_COEFFICIENT = 0.7

    JUMP_GROUND_KNOTS = 20
    JUMP_FLYING_KNOTS = 20

    WALK_STAND_KNOTS = 4
    WALK_TREAD_KNOTS = 20


class CrocoddylConfig:
    CROCODDYL_FORCE_SCALING_FACTOR = 0.0001


class StimuliConfig:
    MIN_GAP_X = 1.5


class PlatformConfig:
    PLATFORM_MASS_WOODY = 10.00
    PLATFORM_MASS_STONE = 20.00

    PLATFORM_HEIGHT = 3.5
    PLATFORM_SIZE_BASE = 3.0
    PLATFORM_SIZE_SLIM = 2.0
    PLATFORM_SIZE_BULK = 4.0
    PLATFORM_SIZE_WALK = 8.0

    PLATFORM_SCALE_TOP_FACTOR = .5
    PLATFORM_SCALE_BOT_FACTOR = .4

    PLATFORM_BEVEL_WIDTH = 0.75
    PLATFORM_BEVEL_SEGMENTS = 20

    PLATFORM_MESH_TYPE = ".stl"


class BlenderConfig:
    VIDEO_FRAME_COUNT = 80
